# The start symbol is TOP.

# These two rules are required; choose their weights carefully!
95  TOP  S1
5   TOP  S2

# This is a very, very, very simple grammar to get you started.

1   S1   NP VP
1   S1   MD _PRP 
1   S1   NP _VP
1   _VP  VP Punc

1   _PRP PRP QOS

1   VP  VerbT NP
1	VP	VerbT JJ

20  NP   Det Nbar
1   NP   Proper

10  Nbar Noun
1   Nbar Nbar PP

1   PP   Prep NP

# in case you use S1.gr by itself
1   S2   Misc
